spring:
  profiles:
    #指定生效的配置
    active: windowsdev
  servlet:
    multipart:
      #设置文件大小
      max-file-size: 10MB
      enabled: true
      max-request-size: 10MB

#mybatis的相关配置
mybatis:
  type-aliases-package: whu.zhj.zhjweb.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


